### ISSUE TITLE
Provide example for Kogito with Business Central

### ISSUE THREAD

**Issue by tokarenko** [apache/incubator-kie-examples#1330]
### Description

I suggest to develop example on how to run Business Central with Kogito.

### Implementation ideas

I thought it was possible to bring up Business Central in a docker container and integrate with Kogito via GIT hooks as described [in KIE blog post](https://blog.kie.org/2021/03/integrate-kogito-and-business-central.html) and by [Alex Porcelli](https://porcelli.me/rhba/business-central/git/2018/11/05/business-central-git.html).

I tried the following container configuration from [stackoverflow](https://stackoverflow.com/questions/71772034/error-when-opening-home-page-in-business-central-when-using-planner-and-rules-pr) and realized that Kogito does not expose kie-server API expected by Business Central. Therefore Business Central may serve just a workspace for collaboration. In his other [blog post](https://porcelli.me/rhba/business-central/git/internals/2018/11/03/business-central-git-internals.html) Alex Porcelli provided rationale for using Business Central's internal git. If this is still valid then I suggest to explore how to run Business Central with Kogito.

```
business-central:
    container_name: business-central-workbench
    image: quay.io/kiegroup/business-central-workbench:latest
    ports:
      - "8680:8080"
      - "8001:8001"
    environment:
      KIE_SERVER_LOCATION: http://${DOCKER_GATEWAY_HOST}:8080/kie-server/services/rest/server
      JAVA_OPTS: "-Xms256m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -Dorg.kie.workbench.profile=FULL"
```
